"""Final-audit adjudication (2026-09-06). Applied by audit_apply.py.

R = {id: (new_code, value, make, justification)}
  new_code : 'I' (kept, note flagged) | 'E1' | 'E2' | 'E3' | 'E4' | 'E6'
  value    : snowballing value for E4 / pool value for E3 ('' = E3 without pool) / primary ID for E6
  make     : 'Make' to set, '' to clear, None to leave as is
  justification : Spanish, quotes verbatim from title/abstract
"""
D = '2026-09-06'

R = {
 # ---- includes recoded to exclusion --------------------------------------------------------
 'R0071': ('E1', '', None,
  'El gemelo es sólo un componente listado de una arquitectura conceptual de corredor multimodal ("a layered digital architecture integrating Internet of Things (IoT) systems, Port Community Systems (PCS), Terminal Operating Systems (TOS), artificial intelligence–based predictive planning, blockchain-enabled documentation, digital twins"), sin gemelo diseñado ni implementado (C1); la IA también sólo listada (E3 secundario). El estudio es socio-técnico e institucional ("semi-quantitative benchmarking of leading smart ports, engineering and functional profiling, and conceptual systems modeling").'),
 'R0081': ('I', '', None,
  'Make conservado tras la verificación independiente: el encuadre de cadena es una pregunta de investigación del propio estudio ("By addressing research questions on optimizing SMS conversion and enhancing supply chain management"), no una frase de cierre (C5), con gemelo piloto y ML ("Leveraging sensor networks and machine learning algorithms, the study presents a pilot implementation using historical data"); verificar en texto completo que el gemelo cubra el flujo de suministro del sustrato y no sólo la conversión.'),
 'R0093': ('E4', 'alto', None,
  'Marco conceptual derivado de revisión de literatura (C3): "this study employs a qualitative research methodology based on an extensive literature review and comparative analysis"; el marco propuesto sí está en la intersección exacta ("integrating AR wearables, digital twins, machine learning, and cyber-physical synchronization standards to optimize material flow processes") con eje humano-céntrico, por eso valor alto.'),
 'R0065': ('E4', 'bajo', None,
  'Marco conceptual basado en revisión (C3): "Based on a structured literature review and an analysis of emerging digital practices, this study proposes a conceptual framework"; gemelo e IA sólo como tecnologías listadas ("IoT, artificial intelligence, blockchain, and digital twins").'),
 'R0007': ('E4', 'bajo', None,
  'Modelo formulado por síntesis de literatura (C3): "the model was formulated by literature synthesis, and it was also checked initially through real life cases studies"; gemelo e IA sólo como habilitadores listados ("artificial intelligence (AI), Internet of Things (IoT), blockchain, and digital twins are essential facilitators of smart manufacturing").'),
 'R0099': ('E4', 'bajo', None,
  'Análisis de tendencias con síntesis de casos (C3): "The research methodology included an analysis of current trends in the field of digital solutions" y "An analysis of real-world case studies was conducted"; dominio de construcción, gemelo sólo como una tecnología más ("digital twins in Singapore, which are used for the management of urban resources").'),
 'R0147': ('E3', 'medio', None,
  'Gemelo conceptual para transporte gestionado con casos simulados ("simulation-based case analyses from both the pharmaceutical industry and logistics systems to conceptually demonstrate the potential benefits of Digital Twins"); la IA sólo como habilitador listado ("leveraging the best technology available today Internet of Things, AI, and cloud computing") y como consigna ("letting machine learning and AI do the work"), sin método ni componente (C8, primera precisión).'),
 'R0134': ('E1', '', None,
  'Exploración del papel de la IA en la planeación portuaria desde la autoridad portuaria; el gemelo no es objeto ni componente diseñado del estudio, sólo tema de integración y plataforma externa ("its integration with Digital Twin technologies", "the Ocean Digital Twin") (C1); la IA sin método (E3 secundario) y la logística sólo como beneficio ("forecasting cargo flows, and im-proving intermodal logistics").'),
 'R0136': ('E4', 'medio', None,
  'Artículo de perspectiva (C3): "This article presents a forward-looking perspective on the development of smart MfgVerse"; gemelos cognitivos e IA en manufactura con eje humano-máquina ("human-centered manufacturing metaverse"), cadena y logística sólo como redes auxiliares ("auxiliary networks of sales, supply chain, logistics, and remanufacturing systems").'),
 'R0117': ('E4', 'medio', None,
  'Síntesis de literatura (C3): "this study compiles and organizes AI in CSC research by identifying the enablers of AI"; cadena circular e IA como objetos, gemelo sólo listado ("technologies such as Digital Twins, Industrial Internet of Things, and Blockchain provide frameworks for cyber-physical systems").'),
 'R0114': ('E4', 'bajo', None,
  'Marco basado en revisión (C3): "This paper, by employing a literature review, introduces a framework that capitalizes on the synergies between VSM and cutting-edge digital twin technology"; dominio de construcción lean, cadena sólo como motivación ("evaluate the efficiency of their value-creation processes and supply chains").'),
 'R0195': ('E1', '', None,
  'Gemelo de diseño y ensamble (C6, modelos de diseño, precedente R0365): "a Risk-Prioritized Digital Twin (RPDT) framework that enables concurrent optimization of design and assembly processes" con FMEA, simulación cinemática y análisis de tolerancias; la cadena sólo como reto mencionado ("supply chain vulnerabilities across numerous sub-components") y la IA sólo como impulsor de demanda.'),
 'R0245': ('E1', '', None,
  'El objeto del texto es la IA y la ciencia de datos en la cadena de valor petrolera; el gemelo no es objeto ni componente del estudio, sólo una aplicación descrita de terceros de forma genérica ("Companies like Shell and Chevron leverage in real-time data from sensors, cameras, and drones to create dynamic representations of operations and equipment") (C1; precedente R0634: un resumen de soluciones de industria no es revisión ni gemelo propio); la IA como técnicas genéricas ("AI techniques like optimization (model creation and updating), generative modelling, data analytics, predictive analytics") (E3 secundario).'),
 'R0234': ('E3', 'medio', None,
  'Modelo conceptual de gemelo de cadena de productos acuáticos ("The DT-based aquatic product supply chain model encompasses 5 layers: perception, data, operation, function, and application"); la IA sólo como requisito sin articular ("the artificial intelligence technologies have to be integrated"), sin método ni papel descrito (C8, primera precisión). Pool medio por gemelo conceptual con cadena central.'),
 'R0275': ('E4', 'medio', None,
  'Panorama declarado (C3): "The article starts by giving a thorough overview of digital twins"; gemelos en operaciones portuarias ("port management, logistics, safety, and environmental sustainability") con el ML sólo como técnica de construcción listada ("emphasizing the incorporation of machine learning, simulation, data analytics, and Internet of Things (IoT) sensors"). Sale del pool Antecedente C8 por ser revisión.'),
 'R0263': ('E4', 'medio', None,
  'Estudio basado en casos y revisiones (C3): "through the use of case studies, literature reviews, and qualitative methods"; gemelos de cadena como objeto ("virtual copies of actual supply chain systems"), IA sólo listada ("Digital Twin (DT), Big Data, artificial intelligence (AI), Internet of Things (IoT), etc."). Sale del pool Antecedente C8 por ser revisión.'),
 'R0217': ('E1', '', None,
  'Estudio de adopción y percepción (C4): encuesta a 106 empresas con análisis de correspondencias ("a structured literature review and a survey were conducted among architecture, engineering, and construction (AEC) firms, with 106 complete responses analyzed using correspondence analysis (CA)"); gemelo e IA como constructos, sin gemelo del estudio; sector construcción (E2 secundario).'),
 'R0288': ('E1', '', None,
  'Texto expositivo sin gemelo del estudio: el gemelo aparece como tecnología de diseño y prototipado ("By optimizing simulation, testing, and design, digital twin technology eliminates the need for physical prototypes") (C1/C6); la cadena sólo como componente listado ("Optimization of the supply chain improves the visibility and sustainability of the supply chain").'),
 'R0207': ('E1', '', None,
  'Texto expositivo sobre IA con IIoT; el gemelo sólo acompaña al monitoreo de procesos ("deep learning techniques and sensor networks together with the digital twin technology to detect bottlenecks") sin sistema propuesto (C1); la cadena sólo como uso listado ("optimize resource allocation, energy efficiency, and supply chain management").'),
 'R0259': ('E4', 'bajo', None,
  'Análisis cualitativo que parte de una revisión del estado del arte y presenta un marco (C3): "The study begins by reviewing the current state-of-the-art technologies on the lunar economy" y "Then a framework for implementation of these technologies is presented"; dominio de economía lunar, cadena sólo como dificultad ("as well as supply chain difficulties").'),
 'R0335': ('E4', 'alto', '',
  'Marco conceptual basado en revisión del estado del arte (C3): "This paper reviews the state of the art and proposes a ZDM strategy-based conceptual framework that models, optimizes and simulates the master production schedule (MPS) problem to maximize service levels in SCs"; intersección exacta gemelo + ML + planeación de cadena ("digital twin (DT) technology, enable new simulation and optimization methods, especially in combination with machine learning (ML) procedures"), por eso valor alto. Make retirado (deja de ser inclusión).'),
 'R0341': ('I', '', None,
  'Make conservado tras la verificación independiente: el objetivo declarado encuadra la cadena ("The goal of this paper is to describe how data from interwoven, autonomous and intelligent supply chains can be integrated into the diverse data ecosystems of the Industry 4.0") (C5) y la inteligencia local de trabajos y materias primas en el avatar digital ("assign local intelligence to jobs and raw materials") es control distribuido tipo agente (C7); verificar en texto completo el método de la inteligencia local y el alcance de cadena del demostrador.'),
 'R0548': ('E1', '', None,
  'Gemelos de prenda para diseño virtual (C6, modelos de diseño): "digital twins, which allow designers to test and refine garment designs virtually"; el estudio evalúa métodos de digitalización de tejidos; la logística sólo como ventaja mencionada ("potential advantages in terms of cost and logistics").'),
 'R0345': ('E1', '', None,
  'Visión de un centro de investigación de intralogística; el gemelo sólo como concepto de escenario emulable ("various real-time scenarios can be emulated including digital twin simulation concepts") sin gemelo del estudio (C1); el ML sólo como posibilidad genérica ("using concepts from machine learning and deep learning networks").'),
 'R0594': ('E1', '', None,
  'Representaciones NFT de componentes ("uses NFTs to create unique, immutable digital representations of physical aviation components") = contenedores de datos (C6, como pasaportes de producto); la cadena es uno de los flujos listados ("part tracking, maintenance records, certification and compliance, supply chain management, flight logs") (E2 secundario); sin IA (E3 secundario).'),
 'R0617': ('E4', 'bajo', None,
  'Columna editorial (C3): texto de opinión sobre extracción de gemelos para sistemas ciberfísicos; la cadena sólo como ejemplo de uso ("they are used to figure out supply chains8 disruptions for manufacturing"), sin estudio.'),
 'R0673': ('E1', '', None,
  'Gemelo de diseño óptico (C6, modelos de diseño): "we have developed a digital-twin and genomic optimization framework for the optical design of vertical indoor farming pods"; la cadena sólo como motivación ("communities at the end of the traditional agriculture supply chain").'),
 'R0389': ('E3', 'medio', None,
  'Concepto temprano de gemelo para la decisión operativa en "production and logistic enterprises" ("a digital twin concept can be applied. These digital twins are virtual clones of real systems or subsystems"); la IA sólo como oportunidad enunciada ("With simulation and artificial intelligence technologies new opportunities for operative decision making are possible"), sin papel articulado en el gemelo, a diferencia de la línea Ivanov (C8, primera precisión). Pool medio por gemelo conceptual con logística de planta central.'),
 'R0133': ('E3', 'medio', None,
  'Panorama con casos secundarios ("how the examples of Unilever and DHL can be used to demonstrate real-life examples"); la IA sólo como etiqueta de los sistemas descritos ("digital twins that are implemented in AI-based logistics systems") sin componente ni papel articulado (C8, primera precisión, criterio aplicado igual que a R0147). Pool medio por panorama de gemelos implementados con cadena central; casos útiles como antecedente.'),
 # ---- companion reports (second appearance removed) -----------------------------------------
 'R0155': ('E6', 'R0152', '',
  'Informe compañero de R0152 (regla de pares: se elimina la segunda aparición): mismo grupo (Mhiri, Kharbeche, Haouari), mismo marco y mismo caso ("The framework is validated on a cryogenic heat exchanger, critical equipment in natural gas liquefaction"), versión de congreso IEEM 2025 que añade LSTM; se conserva el artículo de revista R0152 como informe principal.'),
 'R0315': ('E6', 'R0298', None,
  'Informe compañero de R0298 (regla de pares: se elimina la segunda aparición): mismos autores (Badakhshan y Ball), mismo marco y mismo objetivo ("The proposed SC digital twin framework integrates machine learning (ML) and simulation to identify the inventory replenishment policies that minimize the cash conversion cycle of an SC"), versión de congreso IFAC 2022; se conserva el artículo IJPR R0298.'),
 # ---- includes kept with an explicit full-text flag ------------------------------------------
 'R0022': ('E3', 'medio', None,
  'Artículo conceptual de practicante (Henry Stewart) sobre inteligencia de procesos como gemelo vivo de las operaciones ("Process intelligence addresses this by building a living digital twin of business operations") en cadena y compras; la IA sólo como etiqueta y capacidad ("process-centric approach to enterprise AI", "automate operational decisions in real time"), sin método ni componente (C8, primera precisión; verificación independiente coincidente). Pool medio por gemelo conceptual con cadena central.'),
 'R0530': ('I', '', None,
  'marco de gemelo con IA constitutiva para cadenas logísticas ("a next-generation AI-driven digital twin framework tailored for logistics supply chains") con caso ("A case study on logistics volatility detection"), C8 tercera precisión; riesgo E3 en texto completo si la IA es sólo etiqueta; interés HITL: "DT-aware AI governance" y aseguramiento en tiempo real.'),
 'R0107': ('I', '', None,
  'gemelo implementado ("implementation of a low-cost Digital Twin using an ESP32 microcontroller") en contexto logístico ("fleet management in heavy equipment rental companies"), con el ML como componente propuesto de la arquitectura ("integration with machine learning algorithms is proposed for failure prediction"); se mantiene bajo la tercera precisión de C8 (el Codebook registra que R0107 se sostiene); el texto completo decide si el ML se implementa.'),
 'R0347': ('I', '', None,
  'IA usada aunque sin método nombrado ("digital modeling using artificial intelligence algorithms, and industrial testing at an operating mining facility"), como R0201; logística de planta explícita ("production logistics", "logistics systems"); el texto completo decide qué algoritmos y si el modelo digital opera como gemelo.'),
 'R0080': ('I', '', None,
  'Make más débil (C5): encuadre de cadena por palabra clave y una frase de gestión de operaciones y cadena ("adoption of iDTs in operations and supply chain management"); conservado por su relevancia HITL directa ("keeping humans at the core of the process", ML interpretable y LLM); veto posible.'),
 'R0157': ('I', '', None,
  'el ML se sostiene en "utilizing machine learning to propose sustainability initiatives" y en la palabra clave de autor; confirmar el componente ML de la capa inteligente en texto completo.'),
 'R0118': ('I', '', None,
  'modelo de IA nombrado ("Bayesian Network-Stacked Encoder-Puma Optimizer (BN-SE-PO) model") y cadena en el título; confirmar en texto completo que el gemelo exista más allá de la descripción genérica.'),
 'R0192': ('I', '', None,
  'ML y RL implementados con gemelo de retroalimentación; confirmar el encuadre de cadena ("supply chain forecasting" como escenario analizado) en texto completo.'),
 'R0166': ('I', '', None,
  'encuadre logístico débil ("simulated environments like factories, power grids, and logistics networks"), precedente R0077; el texto completo decide.'),
 'R0142': ('I', '', None,
  'el gemelo es método de validación ("Agent Based Modeling (ABM) and Digital Twin simulations"), no el objeto; el texto completo decide si el gemelo se describe.'),
 'R0639': ('I', '', None,
  'gemelo enunciado como mecanismo ("translated into resilience strategies through optimization and digital-twin simulations") sobre datos simulados; el texto completo decide.'),
 'R0663': ('I', '', None,
  'objeto = simulador gemelo de cadena acelerado con emulación por ML; verificar que el simulador se conserve como gemelo.'),
 'R0551': ('I', '', None,
  'gemelo sólo en título e índice (excepción R0272); verificar en texto completo.'),
 'R0350': ('I', '', None,
  'verificar si el gemelo modela el suministro humanitario o sólo el escenario de peligro (C6).'),
 'R0127': ('I', '', 'Make',
  'Make añadido: gemelos de manufactura aeronáutica con encuadre logístico explícito ("across aviation manufacturing and logistics domains", "logistics inventory optimization", "supply chain networks").'),
}

# ---- snowballing / pool value changes on rows that keep their code ----------------------------
V = {
 'R0049': ('medio', 'bajo', 'la cadena aparece sólo como brecha, no en el alcance declarado'),
 'R0131': ('bajo', 'medio', 'Fashion 5.0 nombra la cadena de moda con eje humano-céntrico y los habilitadores como objeto'),
 'R0250': ('alto', 'medio', 'la intersección exacta requiere gemelos como objeto; aquí sólo se señalan como subrepresentados'),
 'R0228': ('bajo', 'medio', 'cadena nombrada en el alcance y gemelos como tema analizado'),
 'R0257': ('bajo', 'medio', 'cadena humanitaria nombrada e IA como objeto de los casos'),
 'R0304': ('bajo', 'medio', 'logística urbana nombrada y gemelos e IA entre las innovaciones analizadas'),
 'R0582': ('bajo', 'medio', 'Industria 5.0 con eje humano-máquina y cadena como sector nombrado'),
 'R0461': ('bajo', 'medio', 'cadena alimentaria nombrada y gemelos como objeto de simulación predictiva'),
 'R0470': ('bajo', 'medio', 'gestión de cadena como alcance y gemelos e IA como roles emergentes analizados'),
 'R0632': ('medio', 'bajo', 'la cadena no aparece en el alcance declarado'),
}
POOLV = {
 'R0307': ('alto', 'medio', 'la prueba de concepto ilustra un diseño de sistema; el gemelo no está validado en operación'),
}

# ---- cross-links between related reports (note suffix only) ----------------------------------
LINKS = {
 'R0152': 'Informe compañero: R0155 (IEEM 2025) excluido como E6 por la regla de pares; este artículo de revista es el informe principal.',
 'R0298': 'Informe compañero: R0315 (IFAC 2022) excluido como E6 por la regla de pares. R0272 es un estudio distinto del mismo grupo (plan maestro de cadena) y se conserva.',
 'R0272': 'Estudio distinto de R0298/R0315 (mismo grupo): plan maestro bajo disrupciones frente a gestión de inventario y efectivo; se conserva.',
 'R0328': 'Trabajo relacionado: R0331 (IFIP 2021) presenta el marco base; este artículo explora realidad aumentada e interacción humano-máquina sobre ese marco. No se trata como par duplicado; ambos conservados (revisar solapamiento en texto completo).',
 'R0331': 'Trabajo relacionado: R0328 (IFAC 2022) extiende este marco con realidad aumentada e interacción humano-máquina. No se trata como par duplicado; ambos conservados (revisar solapamiento en texto completo).',
 'R0511': 'Trabajo relacionado: R0520 (mismo grupo, gemelo adaptativo con IA agéntica) está incluido.',
 'R0520': 'Trabajo relacionado: R0511 (mismo grupo, arquitectura previa sin método de IA) está en el pool Antecedente C8.',
 'R0676': 'Trabajo relacionado: R0551 (mismo proyecto de almacén TRUSCO NAKAYAMA) está incluido.',
 'R0672': 'Trabajo relacionado: R0307 (mismo grupo, gemelo de logística inversa) está en el pool Antecedente C8.',
 'R0653': 'Aunque E1, su lista de referencias (Ivanov 2025, Industria 5.0 y centralidad humana) es útil para el snowballing manual desde los incluidos de la línea Ivanov.',
}
