"""Append the final-audit rows to the Codebook (run after audit_apply.py). usage: python3 audit_codebook.py <workbook>"""
import os as _os, sys as _sys; _sys.path.insert(0, _os.path.dirname(_os.path.abspath(__file__)))
import openpyxl, sys, re, collections
from copy import copy
path = sys.argv[1]
wb = openpyxl.load_workbook(path)
ws = wb['Screening']; cb = wb['Codebook']
from screening_cols import cols
C = cols(ws)
# ---- live totals for the closure row ----
codes = collections.Counter(ws.cell(r, C('Código final')).value for r in range(2, ws.max_row + 1))
e4v = collections.Counter(); c8v = collections.Counter(); n_make = 0
for r in range(2, ws.max_row + 1):
    n = ws.cell(r, C('Notes')).value or ''; o = ws.cell(r, C('Código final')).value
    if o == 'E4':
        e4v[re.search(r'snowballing\s*:\s*(alto|medio|bajo)', n, re.I).group(1).lower()] += 1
    if o == 'E3' and 'Antecedente C8' in n:
        c8v[re.search(r'Antecedente C8\s*:\s*(alto|medio|bajo)', n).group(1)] += 1
    if ws.cell(r, C('Decision')).value == 'Include' and ws.cell(r, C('Nota Make')).value == 'Make':
        n_make += 1
n_incl = codes['I']; n_excl = 712 - n_incl
assert cb.cell(62, 1).value == 'Title/abstract screening closed', cb.cell(62, 1).value
cb.cell(62, 1).value = 'Title/abstract screening closed (provisional, before the final audit)'
cb.cell(62, 3).value = 'Provisional closure. ' + cb.cell(62, 3).value + ' Superseded by the final-audit closure row below.'
rows = [
 ('Final audit of all 712 decisions', 'Applied 2026-09-06',
  'Instruction of the screener of record: re-check every decision, apply judgement to the weak sensitivity includes with the dissertation context in view, and for companion reports always remove the second appearance. Six independent re-screenings (groups A to F) were run over the final decisions, adjudicated, and the adjudication itself was checked by a seventh independent screener before being written. Result: 30 recodes (each Notes entry begins with "Recodificado 2026-09-06 en la auditoría final" and keeps the original note), 16 includes kept with an explicit full-text flag ("Auditoría final 2026-09-06: se mantiene I"), 10 snowballing values recalibrated, 1 pool value adjusted, 1 Make annotation added, 10 cross-links between related reports. Recodes: I→E1 R0071, R0134; I→E3 (pool) R0022, R0147, R0133, R0234, R0389; I→E4 R0093 (alto), R0335 (alto); I→E6 R0155, R0315; E1→E4 R0065, R0007, R0117; E2→E4 R0099, R0114, R0136, R0259, R0617; E2→E1 R0195, R0217, R0288, R0207, R0548, R0594, R0673; I→E1 R0245; E3→E4 R0275, R0263; E3→E1 R0345. Make added to R0127; Make removed with the recodes of R0335 and R0155. Kept with flag: R0080, R0081, R0107, R0118, R0127, R0142, R0157, R0166, R0192, R0341, R0347, R0350, R0530, R0551, R0639, R0663. Items the screener of record may still veto are listed in the closing report of 2026-09-06.'),
 ('Decision rule: companion reports (pairs)', 'Ruled 2026-09-06 by the screener of record',
  'When two records report the same study (same authors, same framework and same case, typically a conference version and a journal version), the second appearance is excluded as E6 with the exclusion reason "Duplicate" and the note "informe compañero de R0xxx"; the first appearance (the journal article where one exists) is the primary report and its note names the companion. In the PRISMA flow these E6 records are reported as "companion reports of included studies" (PRISMA 2020 counts reports, not studies), not as retrieval duplicates. Applied: R0155 → E6 (companion of R0152), R0315 → E6 (companion of R0298). Distinct studies by the same group are NOT pairs and are all kept: R0272 (master planning under disruptions) versus R0298 (inventory and cash management); R0331 (framework) versus R0328 (augmented reality and human-machine interaction on that framework) — both kept, cross-linked, overlap to be checked at full text. Where the second report was already excluded on its own merits (R0511/R0520, R0676/R0551, R0672/R0307, R0490) only a cross-link was added.'),
 ('Clarification of C3 applied in the final audit: review as the primary method or genre', 'Ruled 2026-09-06 (final audit)',
  'C3 applies when a review-type method or genre is the sole or primary basis of the record: a literature review or literature synthesis as the basis of a conceptual framework (R0065, R0007, R0093, R0114, R0335), a perspective or position article (R0136), a compilation of a research stream (R0117), a trend analysis with secondary case synthesis (R0099), a state-of-the-art review followed by a framework (R0259), a declared overview (R0275), a study built on case studies and literature reviews (R0263), an editorial column (R0617). These are E4 with a snowballing value even when they sit in the exact intersection (R0093 and R0335 carry alto). C3 does not apply when a literature review or bibliometric analysis is only preparatory to another primary method: an adoption survey follows C4 (R0217 → E1); a proposed and validated system with a bibliometric gap analysis is screened on its system (R0142 → I). A summary of third-party industry solutions without a twin of the study is not a review (R0634, R0245 → E1). Theory-building conceptual papers that do not rest on a declared review and whose object is the AI-enabled supply chain twin remain includes (Ivanov line: R0011, R0084, R0137, R0273, R0309, R0554, R0614, R0664). Expository papers with no declared review method and no twin of their own follow C1/C2 (R0207, R0288 → E1).'),
 ('Clarification of C8 applied in the final audit: label versus articulated role', 'Ruled 2026-09-06 (final audit)',
  'Descriptive or conceptual papers in which AI is only a label or a capability of the systems described ("AI-based logistics systems", "AI-driven supply chain optimization", "letting machine learning and AI do the work", "the artificial intelligence technologies have to be integrated", "enterprise AI", "with simulation and artificial intelligence technologies new opportunities ... are possible") do not meet criterion 3 and go to E3 with an Antecedente C8 tag when the twin and the setting are central (R0022, R0147, R0133, R0234, R0389 → E3 medio). The Ivanov-line includes differ because the abstract articulates the role of AI inside the twin concept (AI-based knowledge management systems and a human-AI collaboration space in R0554; AI and simulation integrating to describe, predict and optimise in R0614; OR-AI symbiosis architecture in R0011; agentic AI triangulated with digital twins in R0084). R0530 (AI-driven digital twin framework for logistics supply chains with a volatility-detection case) stands under the third ruling as recorded on 2026-09-06, as do R0107 (implemented forklift twin, ML a proposed component of the architecture) and R0157; papers that USE AI without naming the method also stand (R0347 "digital modeling using artificial intelligence algorithms" with industrial testing; R0201 AI-processed images). Full text decides all of these; they are flagged in Notes.'),
 ('Note on C5 in the final audit (R0080, R0081, R0118, R0192, R0341)', 'Ruled 2026-09-06 (final audit)',
  'C5 is applied leniently but uniformly at title/abstract: the supply chain or logistics framing qualifies when it is part of the study as stated — a declared goal (R0341 "how data from interwoven, autonomous and intelligent supply chains can be integrated"), a research question (R0081 "enhancing supply chain management"), the title and closing framing of an empirical study (R0118), an analysed scenario (R0192 "supply chain forecasting") or an explicit operations-and-supply-chain-management framing (R0080 "adoption of iDTs in operations and supply chain management", also a direct human-in-the-loop example). Only a generic benefit sentence detached from the study (R0033, R0088, R0586 and the other E2 precedents) fails. All five are kept as Make includes with a full-text flag; the screener of record may veto any of them, R0080 being the weakest.'),
 ('Snowballing values recalibrated in the final audit', 'Applied 2026-09-06',
  'Ten E4 values were realigned to the snowballing criterion and the change is recorded in each note ("ajustado en la auditoría final 2026-09-06, antes ..."): R0049 medio→bajo; R0632 medio→bajo; R0250 alto→medio; R0131, R0228, R0257, R0304, R0582, R0461, R0470 bajo→medio. Pool value R0307 alto→medio (proof of concept of a system design, not an operating twin).'),
 ('Title/abstract screening closed after the final audit', '2026-09-06',
  f'All 712 records screened, confirmed and audited. Included for full-text retrieval: {n_incl} ({n_make} with the Make annotation). Excluded: {n_excl} = E1 {codes["E1"]} (no digital twin/model), E2 {codes["E2"]} (no supply chain/logistics scope or out-of-scope domain), E3 {codes["E3"]} (no AI/ML), E4 {codes["E4"]} (reviews and other non-primary publication types, retained for backward snowballing: alto {e4v["alto"]}, medio {e4v["medio"]}, bajo {e4v["bajo"]}), E5 {codes["E5"]} (4 not in English, 1 extended abstract), E6 {codes["E6"]} (companion reports of included studies). Retained for background: {sum(c8v.values())} E3 records tagged Antecedente C8 (alto {c8v["alto"]}, medio {c8v["medio"]}). Sheets Includes_fulltext, Snowballing_E4 and Antecedentes_C8 list the three pools. Next stage: retrieval and full-text eligibility (PRISMA_log rows 12 to 22); the Coding sheet is pre-populated with the {n_incl} includes.'),
]
src = [cb.cell(row=24, column=c) for c in (1, 2, 3)]
r0 = cb.max_row
assert r0 == 62, r0
for i, vals in enumerate(rows, start=1):
    for c, v in enumerate(vals, start=1):
        cell = cb.cell(row=r0 + i, column=c, value=v); s = src[c - 1]
        cell.font = copy(s.font); cell.border = copy(s.border); cell.fill = copy(s.fill); cell.alignment = copy(s.alignment)
wb.save(path)
print('Codebook rows', cb.max_row, '| closure:', rows[-1][2][:200])
